/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AnimatableProperty = { 'rotation' : null } |
  { 'shake_intensity' : null } |
  { 'effect_intensity' : null } |
  { 'scale_x' : null } |
  { 'scale_y' : null } |
  { 'blur_radius' : null } |
  { 'position_x' : null } |
  { 'position_y' : null } |
  { 'hue_shift' : null } |
  { 'shake_speed' : null } |
  { 'opacity' : null } |
  { 'saturation' : null };
export interface Clip {
  'id' : ClipId,
  'duration' : number,
  'keyframeTracks' : Array<KeyframeTrack>,
  'trimOut' : number,
  'effects' : Array<Effect>,
  'colorFilter' : ColorFilter,
  'trimIn' : number,
  'transition' : [] | [Transition],
  'clipType' : ClipType,
  'volume' : number,
  'textProps' : [] | [TextClipProps],
  'speed' : number,
  'trackId' : TrackId,
  'position' : bigint,
  'fileRef' : string,
}
export type ClipId = bigint;
export type ClipType = { 'audio' : null } |
  { 'video' : null } |
  { 'text' : null } |
  { 'image' : null };
export interface ColorFilter {
  'contrast' : number,
  'hueRotation' : number,
  'brightness' : number,
  'opacity' : number,
  'saturation' : number,
}
export type EasingType = { 'easeInOut' : null } |
  { 'bounce' : null } |
  { 'easeIn' : null } |
  { 'easeOut' : null } |
  { 'linear' : null };
export interface Effect {
  'id' : EffectId,
  'keyframeTracks' : Array<KeyframeTrack>,
  'effectType' : EffectType,
  'params' : Array<[string, number]>,
}
export type EffectId = bigint;
export interface EffectPreset {
  'id' : PresetId,
  'name' : string,
  'creatorId' : Principal,
  'effectType' : EffectType,
  'isPublic' : boolean,
  'params' : Array<[string, number]>,
}
export type EffectType = { 'blur' : null } |
  { 'shake' : null } |
  { 'colorShift' : null };
export interface Keyframe {
  'id' : KeyframeId,
  'value' : number,
  'time' : number,
  'easing' : EasingType,
}
export type KeyframeId = bigint;
export interface KeyframeTrack {
  'keyframes' : Array<Keyframe>,
  'propertyName' : AnimatableProperty,
}
export interface MusicTrack {
  'muted' : boolean,
  'volume' : number,
  'fileRef' : string,
}
export type PresetId = bigint;
export interface Project {
  'musicTrack' : [] | [MusicTrack],
  'meta' : ProjectMeta,
  'clips' : Array<Clip>,
}
export type ProjectId = bigint;
export interface ProjectMeta {
  'id' : ProjectId,
  'owner' : Principal,
  'name' : string,
  'createdAt' : Time,
  'totalDuration' : number,
  'lastModified' : Time,
}
export interface TextClipProps {
  'italic' : boolean,
  'content' : string,
  'bold' : boolean,
  'fontFamily' : string,
  'fontSize' : number,
  'alignment' : { 'center' : null } |
    { 'left' : null } |
    { 'right' : null },
  'fontColor' : string,
}
export type Theme = { 'dark' : null } |
  { 'light' : null };
export type Time = bigint;
export interface TimelineSnapshot {
  'musicTrack' : [] | [MusicTrack],
  'clips' : Array<Clip>,
}
export type TrackId = bigint;
export interface Transition {
  'duration' : number,
  'transitionType' : TransitionType,
}
export interface TransitionPreset {
  'id' : PresetId,
  'name' : string,
  'creatorId' : Principal,
  'transitionType' : TransitionType__1,
  'isPublic' : boolean,
  'params' : Array<[string, number]>,
}
export type TransitionType = { 'zoom' : null } |
  { 'fadeToBlack' : null } |
  { 'slide' : null } |
  { 'crossfade' : null } |
  { 'dissolve' : null };
export type TransitionType__1 = { 'blur' : null } |
  { 'spin' : null } |
  { 'zoom' : null } |
  { 'fadeToBlack' : null } |
  { 'slide' : null } |
  { 'crossfade' : null } |
  { 'glitch' : null } |
  { 'dissolve' : null };
export interface UserPreferences { 'theme' : Theme }
export interface _SERVICE {
  'addClip' : ActorMethod<
    [ProjectId, TrackId, string, ClipType, number],
    ClipId
  >,
  'addEffect' : ActorMethod<
    [ProjectId, ClipId, EffectType, Array<[string, number]>],
    EffectId
  >,
  'addKeyframe' : ActorMethod<
    [ProjectId, ClipId, AnimatableProperty, number, number, EasingType],
    KeyframeId
  >,
  'createProject' : ActorMethod<[string], ProjectMeta>,
  'deletePreset' : ActorMethod<[PresetId, boolean], undefined>,
  'deleteProject' : ActorMethod<[ProjectId], undefined>,
  'getClipKeyframeTracks' : ActorMethod<
    [ProjectId, ClipId],
    Array<KeyframeTrack>
  >,
  'getProject' : ActorMethod<[ProjectId], [] | [Project]>,
  'getUserPreferences' : ActorMethod<[], UserPreferences>,
  'listEffectPresets' : ActorMethod<[], Array<EffectPreset>>,
  'listProjects' : ActorMethod<[], Array<ProjectMeta>>,
  'listTransitionPresets' : ActorMethod<[], Array<TransitionPreset>>,
  'redo' : ActorMethod<[ProjectId], [] | [TimelineSnapshot]>,
  'removeClip' : ActorMethod<[ProjectId, ClipId], undefined>,
  'removeEffect' : ActorMethod<[ProjectId, ClipId, EffectId], undefined>,
  'removeKeyframe' : ActorMethod<
    [ProjectId, ClipId, AnimatableProperty, KeyframeId],
    undefined
  >,
  'removeMusicTrack' : ActorMethod<[ProjectId], undefined>,
  'renameProject' : ActorMethod<[ProjectId, string], undefined>,
  'reorderClip' : ActorMethod<[ProjectId, ClipId, bigint], undefined>,
  'saveEffectPreset' : ActorMethod<
    [string, EffectType, Array<[string, number]>, boolean],
    PresetId
  >,
  'saveProject' : ActorMethod<[ProjectId], ProjectMeta>,
  'saveTransitionPreset' : ActorMethod<
    [string, TransitionType__1, Array<[string, number]>, boolean],
    PresetId
  >,
  'setMusicTrack' : ActorMethod<[ProjectId, string, number], undefined>,
  'setUserPreferences' : ActorMethod<[UserPreferences], undefined>,
  'undo' : ActorMethod<[ProjectId], [] | [TimelineSnapshot]>,
  'updateClip' : ActorMethod<
    [
      ProjectId,
      ClipId,
      [] | [string],
      [] | [number],
      [] | [number],
      [] | [number],
      [] | [number],
      [] | [ColorFilter],
      [] | [[] | [Transition]],
    ],
    undefined
  >,
  'updateEffect' : ActorMethod<
    [ProjectId, ClipId, EffectId, Array<[string, number]>],
    undefined
  >,
  'updateKeyframe' : ActorMethod<
    [
      ProjectId,
      ClipId,
      AnimatableProperty,
      KeyframeId,
      [] | [number],
      [] | [EasingType],
    ],
    undefined
  >,
  'updateMusicTrack' : ActorMethod<
    [ProjectId, [] | [number], [] | [boolean]],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];