/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ProjectId = IDL.Nat;
export const TrackId = IDL.Nat;
export const ClipType = IDL.Variant({
  'audio' : IDL.Null,
  'video' : IDL.Null,
  'text' : IDL.Null,
  'image' : IDL.Null,
});
export const ClipId = IDL.Nat;
export const EffectType = IDL.Variant({
  'blur' : IDL.Null,
  'shake' : IDL.Null,
  'colorShift' : IDL.Null,
});
export const EffectId = IDL.Nat;
export const AnimatableProperty = IDL.Variant({
  'rotation' : IDL.Null,
  'shake_intensity' : IDL.Null,
  'effect_intensity' : IDL.Null,
  'scale_x' : IDL.Null,
  'scale_y' : IDL.Null,
  'blur_radius' : IDL.Null,
  'position_x' : IDL.Null,
  'position_y' : IDL.Null,
  'hue_shift' : IDL.Null,
  'shake_speed' : IDL.Null,
  'opacity' : IDL.Null,
  'saturation' : IDL.Null,
});
export const EasingType = IDL.Variant({
  'easeInOut' : IDL.Null,
  'bounce' : IDL.Null,
  'easeIn' : IDL.Null,
  'easeOut' : IDL.Null,
  'linear' : IDL.Null,
});
export const KeyframeId = IDL.Nat;
export const Time = IDL.Int;
export const ProjectMeta = IDL.Record({
  'id' : ProjectId,
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : Time,
  'totalDuration' : IDL.Float64,
  'lastModified' : Time,
});
export const PresetId = IDL.Nat;
export const Keyframe = IDL.Record({
  'id' : KeyframeId,
  'value' : IDL.Float64,
  'time' : IDL.Float64,
  'easing' : EasingType,
});
export const KeyframeTrack = IDL.Record({
  'keyframes' : IDL.Vec(Keyframe),
  'propertyName' : AnimatableProperty,
});
export const MusicTrack = IDL.Record({
  'muted' : IDL.Bool,
  'volume' : IDL.Float64,
  'fileRef' : IDL.Text,
});
export const Effect = IDL.Record({
  'id' : EffectId,
  'keyframeTracks' : IDL.Vec(KeyframeTrack),
  'effectType' : EffectType,
  'params' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64)),
});
export const ColorFilter = IDL.Record({
  'contrast' : IDL.Float64,
  'hueRotation' : IDL.Float64,
  'brightness' : IDL.Float64,
  'opacity' : IDL.Float64,
  'saturation' : IDL.Float64,
});
export const TransitionType = IDL.Variant({
  'zoom' : IDL.Null,
  'fadeToBlack' : IDL.Null,
  'slide' : IDL.Null,
  'crossfade' : IDL.Null,
  'dissolve' : IDL.Null,
});
export const Transition = IDL.Record({
  'duration' : IDL.Float64,
  'transitionType' : TransitionType,
});
export const TextClipProps = IDL.Record({
  'italic' : IDL.Bool,
  'content' : IDL.Text,
  'bold' : IDL.Bool,
  'fontFamily' : IDL.Text,
  'fontSize' : IDL.Float64,
  'alignment' : IDL.Variant({
    'center' : IDL.Null,
    'left' : IDL.Null,
    'right' : IDL.Null,
  }),
  'fontColor' : IDL.Text,
});
export const Clip = IDL.Record({
  'id' : ClipId,
  'duration' : IDL.Float64,
  'keyframeTracks' : IDL.Vec(KeyframeTrack),
  'trimOut' : IDL.Float64,
  'effects' : IDL.Vec(Effect),
  'colorFilter' : ColorFilter,
  'trimIn' : IDL.Float64,
  'transition' : IDL.Opt(Transition),
  'clipType' : ClipType,
  'volume' : IDL.Float64,
  'textProps' : IDL.Opt(TextClipProps),
  'speed' : IDL.Float64,
  'trackId' : TrackId,
  'position' : IDL.Nat,
  'fileRef' : IDL.Text,
});
export const Project = IDL.Record({
  'musicTrack' : IDL.Opt(MusicTrack),
  'meta' : ProjectMeta,
  'clips' : IDL.Vec(Clip),
});
export const Theme = IDL.Variant({ 'dark' : IDL.Null, 'light' : IDL.Null });
export const UserPreferences = IDL.Record({ 'theme' : Theme });
export const EffectPreset = IDL.Record({
  'id' : PresetId,
  'name' : IDL.Text,
  'creatorId' : IDL.Principal,
  'effectType' : EffectType,
  'isPublic' : IDL.Bool,
  'params' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64)),
});
export const TransitionType__1 = IDL.Variant({
  'blur' : IDL.Null,
  'spin' : IDL.Null,
  'zoom' : IDL.Null,
  'fadeToBlack' : IDL.Null,
  'slide' : IDL.Null,
  'crossfade' : IDL.Null,
  'glitch' : IDL.Null,
  'dissolve' : IDL.Null,
});
export const TransitionPreset = IDL.Record({
  'id' : PresetId,
  'name' : IDL.Text,
  'creatorId' : IDL.Principal,
  'transitionType' : TransitionType__1,
  'isPublic' : IDL.Bool,
  'params' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64)),
});
export const TimelineSnapshot = IDL.Record({
  'musicTrack' : IDL.Opt(MusicTrack),
  'clips' : IDL.Vec(Clip),
});

export const idlService = IDL.Service({
  'addClip' : IDL.Func(
      [ProjectId, TrackId, IDL.Text, ClipType, IDL.Float64],
      [ClipId],
      [],
    ),
  'addEffect' : IDL.Func(
      [
        ProjectId,
        ClipId,
        EffectType,
        IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64)),
      ],
      [EffectId],
      [],
    ),
  'addKeyframe' : IDL.Func(
      [
        ProjectId,
        ClipId,
        AnimatableProperty,
        IDL.Float64,
        IDL.Float64,
        EasingType,
      ],
      [KeyframeId],
      [],
    ),
  'createProject' : IDL.Func([IDL.Text], [ProjectMeta], []),
  'deletePreset' : IDL.Func([PresetId, IDL.Bool], [], []),
  'deleteProject' : IDL.Func([ProjectId], [], []),
  'getClipKeyframeTracks' : IDL.Func(
      [ProjectId, ClipId],
      [IDL.Vec(KeyframeTrack)],
      ['query'],
    ),
  'getProject' : IDL.Func([ProjectId], [IDL.Opt(Project)], ['query']),
  'getUserPreferences' : IDL.Func([], [UserPreferences], ['query']),
  'listEffectPresets' : IDL.Func([], [IDL.Vec(EffectPreset)], ['query']),
  'listProjects' : IDL.Func([], [IDL.Vec(ProjectMeta)], ['query']),
  'listTransitionPresets' : IDL.Func(
      [],
      [IDL.Vec(TransitionPreset)],
      ['query'],
    ),
  'redo' : IDL.Func([ProjectId], [IDL.Opt(TimelineSnapshot)], []),
  'removeClip' : IDL.Func([ProjectId, ClipId], [], []),
  'removeEffect' : IDL.Func([ProjectId, ClipId, EffectId], [], []),
  'removeKeyframe' : IDL.Func(
      [ProjectId, ClipId, AnimatableProperty, KeyframeId],
      [],
      [],
    ),
  'removeMusicTrack' : IDL.Func([ProjectId], [], []),
  'renameProject' : IDL.Func([ProjectId, IDL.Text], [], []),
  'reorderClip' : IDL.Func([ProjectId, ClipId, IDL.Nat], [], []),
  'saveEffectPreset' : IDL.Func(
      [
        IDL.Text,
        EffectType,
        IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64)),
        IDL.Bool,
      ],
      [PresetId],
      [],
    ),
  'saveProject' : IDL.Func([ProjectId], [ProjectMeta], []),
  'saveTransitionPreset' : IDL.Func(
      [
        IDL.Text,
        TransitionType__1,
        IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64)),
        IDL.Bool,
      ],
      [PresetId],
      [],
    ),
  'setMusicTrack' : IDL.Func([ProjectId, IDL.Text, IDL.Float64], [], []),
  'setUserPreferences' : IDL.Func([UserPreferences], [], []),
  'undo' : IDL.Func([ProjectId], [IDL.Opt(TimelineSnapshot)], []),
  'updateClip' : IDL.Func(
      [
        ProjectId,
        ClipId,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Float64),
        IDL.Opt(IDL.Float64),
        IDL.Opt(IDL.Float64),
        IDL.Opt(IDL.Float64),
        IDL.Opt(ColorFilter),
        IDL.Opt(IDL.Opt(Transition)),
      ],
      [],
      [],
    ),
  'updateEffect' : IDL.Func(
      [ProjectId, ClipId, EffectId, IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64))],
      [],
      [],
    ),
  'updateKeyframe' : IDL.Func(
      [
        ProjectId,
        ClipId,
        AnimatableProperty,
        KeyframeId,
        IDL.Opt(IDL.Float64),
        IDL.Opt(EasingType),
      ],
      [],
      [],
    ),
  'updateMusicTrack' : IDL.Func(
      [ProjectId, IDL.Opt(IDL.Float64), IDL.Opt(IDL.Bool)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ProjectId = IDL.Nat;
  const TrackId = IDL.Nat;
  const ClipType = IDL.Variant({
    'audio' : IDL.Null,
    'video' : IDL.Null,
    'text' : IDL.Null,
    'image' : IDL.Null,
  });
  const ClipId = IDL.Nat;
  const EffectType = IDL.Variant({
    'blur' : IDL.Null,
    'shake' : IDL.Null,
    'colorShift' : IDL.Null,
  });
  const EffectId = IDL.Nat;
  const AnimatableProperty = IDL.Variant({
    'rotation' : IDL.Null,
    'shake_intensity' : IDL.Null,
    'effect_intensity' : IDL.Null,
    'scale_x' : IDL.Null,
    'scale_y' : IDL.Null,
    'blur_radius' : IDL.Null,
    'position_x' : IDL.Null,
    'position_y' : IDL.Null,
    'hue_shift' : IDL.Null,
    'shake_speed' : IDL.Null,
    'opacity' : IDL.Null,
    'saturation' : IDL.Null,
  });
  const EasingType = IDL.Variant({
    'easeInOut' : IDL.Null,
    'bounce' : IDL.Null,
    'easeIn' : IDL.Null,
    'easeOut' : IDL.Null,
    'linear' : IDL.Null,
  });
  const KeyframeId = IDL.Nat;
  const Time = IDL.Int;
  const ProjectMeta = IDL.Record({
    'id' : ProjectId,
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : Time,
    'totalDuration' : IDL.Float64,
    'lastModified' : Time,
  });
  const PresetId = IDL.Nat;
  const Keyframe = IDL.Record({
    'id' : KeyframeId,
    'value' : IDL.Float64,
    'time' : IDL.Float64,
    'easing' : EasingType,
  });
  const KeyframeTrack = IDL.Record({
    'keyframes' : IDL.Vec(Keyframe),
    'propertyName' : AnimatableProperty,
  });
  const MusicTrack = IDL.Record({
    'muted' : IDL.Bool,
    'volume' : IDL.Float64,
    'fileRef' : IDL.Text,
  });
  const Effect = IDL.Record({
    'id' : EffectId,
    'keyframeTracks' : IDL.Vec(KeyframeTrack),
    'effectType' : EffectType,
    'params' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64)),
  });
  const ColorFilter = IDL.Record({
    'contrast' : IDL.Float64,
    'hueRotation' : IDL.Float64,
    'brightness' : IDL.Float64,
    'opacity' : IDL.Float64,
    'saturation' : IDL.Float64,
  });
  const TransitionType = IDL.Variant({
    'zoom' : IDL.Null,
    'fadeToBlack' : IDL.Null,
    'slide' : IDL.Null,
    'crossfade' : IDL.Null,
    'dissolve' : IDL.Null,
  });
  const Transition = IDL.Record({
    'duration' : IDL.Float64,
    'transitionType' : TransitionType,
  });
  const TextClipProps = IDL.Record({
    'italic' : IDL.Bool,
    'content' : IDL.Text,
    'bold' : IDL.Bool,
    'fontFamily' : IDL.Text,
    'fontSize' : IDL.Float64,
    'alignment' : IDL.Variant({
      'center' : IDL.Null,
      'left' : IDL.Null,
      'right' : IDL.Null,
    }),
    'fontColor' : IDL.Text,
  });
  const Clip = IDL.Record({
    'id' : ClipId,
    'duration' : IDL.Float64,
    'keyframeTracks' : IDL.Vec(KeyframeTrack),
    'trimOut' : IDL.Float64,
    'effects' : IDL.Vec(Effect),
    'colorFilter' : ColorFilter,
    'trimIn' : IDL.Float64,
    'transition' : IDL.Opt(Transition),
    'clipType' : ClipType,
    'volume' : IDL.Float64,
    'textProps' : IDL.Opt(TextClipProps),
    'speed' : IDL.Float64,
    'trackId' : TrackId,
    'position' : IDL.Nat,
    'fileRef' : IDL.Text,
  });
  const Project = IDL.Record({
    'musicTrack' : IDL.Opt(MusicTrack),
    'meta' : ProjectMeta,
    'clips' : IDL.Vec(Clip),
  });
  const Theme = IDL.Variant({ 'dark' : IDL.Null, 'light' : IDL.Null });
  const UserPreferences = IDL.Record({ 'theme' : Theme });
  const EffectPreset = IDL.Record({
    'id' : PresetId,
    'name' : IDL.Text,
    'creatorId' : IDL.Principal,
    'effectType' : EffectType,
    'isPublic' : IDL.Bool,
    'params' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64)),
  });
  const TransitionType__1 = IDL.Variant({
    'blur' : IDL.Null,
    'spin' : IDL.Null,
    'zoom' : IDL.Null,
    'fadeToBlack' : IDL.Null,
    'slide' : IDL.Null,
    'crossfade' : IDL.Null,
    'glitch' : IDL.Null,
    'dissolve' : IDL.Null,
  });
  const TransitionPreset = IDL.Record({
    'id' : PresetId,
    'name' : IDL.Text,
    'creatorId' : IDL.Principal,
    'transitionType' : TransitionType__1,
    'isPublic' : IDL.Bool,
    'params' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64)),
  });
  const TimelineSnapshot = IDL.Record({
    'musicTrack' : IDL.Opt(MusicTrack),
    'clips' : IDL.Vec(Clip),
  });
  
  return IDL.Service({
    'addClip' : IDL.Func(
        [ProjectId, TrackId, IDL.Text, ClipType, IDL.Float64],
        [ClipId],
        [],
      ),
    'addEffect' : IDL.Func(
        [
          ProjectId,
          ClipId,
          EffectType,
          IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64)),
        ],
        [EffectId],
        [],
      ),
    'addKeyframe' : IDL.Func(
        [
          ProjectId,
          ClipId,
          AnimatableProperty,
          IDL.Float64,
          IDL.Float64,
          EasingType,
        ],
        [KeyframeId],
        [],
      ),
    'createProject' : IDL.Func([IDL.Text], [ProjectMeta], []),
    'deletePreset' : IDL.Func([PresetId, IDL.Bool], [], []),
    'deleteProject' : IDL.Func([ProjectId], [], []),
    'getClipKeyframeTracks' : IDL.Func(
        [ProjectId, ClipId],
        [IDL.Vec(KeyframeTrack)],
        ['query'],
      ),
    'getProject' : IDL.Func([ProjectId], [IDL.Opt(Project)], ['query']),
    'getUserPreferences' : IDL.Func([], [UserPreferences], ['query']),
    'listEffectPresets' : IDL.Func([], [IDL.Vec(EffectPreset)], ['query']),
    'listProjects' : IDL.Func([], [IDL.Vec(ProjectMeta)], ['query']),
    'listTransitionPresets' : IDL.Func(
        [],
        [IDL.Vec(TransitionPreset)],
        ['query'],
      ),
    'redo' : IDL.Func([ProjectId], [IDL.Opt(TimelineSnapshot)], []),
    'removeClip' : IDL.Func([ProjectId, ClipId], [], []),
    'removeEffect' : IDL.Func([ProjectId, ClipId, EffectId], [], []),
    'removeKeyframe' : IDL.Func(
        [ProjectId, ClipId, AnimatableProperty, KeyframeId],
        [],
        [],
      ),
    'removeMusicTrack' : IDL.Func([ProjectId], [], []),
    'renameProject' : IDL.Func([ProjectId, IDL.Text], [], []),
    'reorderClip' : IDL.Func([ProjectId, ClipId, IDL.Nat], [], []),
    'saveEffectPreset' : IDL.Func(
        [
          IDL.Text,
          EffectType,
          IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64)),
          IDL.Bool,
        ],
        [PresetId],
        [],
      ),
    'saveProject' : IDL.Func([ProjectId], [ProjectMeta], []),
    'saveTransitionPreset' : IDL.Func(
        [
          IDL.Text,
          TransitionType__1,
          IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64)),
          IDL.Bool,
        ],
        [PresetId],
        [],
      ),
    'setMusicTrack' : IDL.Func([ProjectId, IDL.Text, IDL.Float64], [], []),
    'setUserPreferences' : IDL.Func([UserPreferences], [], []),
    'undo' : IDL.Func([ProjectId], [IDL.Opt(TimelineSnapshot)], []),
    'updateClip' : IDL.Func(
        [
          ProjectId,
          ClipId,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Float64),
          IDL.Opt(IDL.Float64),
          IDL.Opt(IDL.Float64),
          IDL.Opt(IDL.Float64),
          IDL.Opt(ColorFilter),
          IDL.Opt(IDL.Opt(Transition)),
        ],
        [],
        [],
      ),
    'updateEffect' : IDL.Func(
        [
          ProjectId,
          ClipId,
          EffectId,
          IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64)),
        ],
        [],
        [],
      ),
    'updateKeyframe' : IDL.Func(
        [
          ProjectId,
          ClipId,
          AnimatableProperty,
          KeyframeId,
          IDL.Opt(IDL.Float64),
          IDL.Opt(EasingType),
        ],
        [],
        [],
      ),
    'updateMusicTrack' : IDL.Func(
        [ProjectId, IDL.Opt(IDL.Float64), IDL.Opt(IDL.Bool)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };