/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Project {
    musicTrack?: MusicTrack;
    meta: ProjectMeta;
    clips: Array<Clip>;
}
export type EffectId = bigint;
export interface UserPreferences {
    theme: Theme;
}
export interface TransitionPreset {
    id: PresetId;
    name: string;
    creatorId: Principal;
    transitionType: TransitionType__1;
    isPublic: boolean;
    params: Array<[string, number]>;
}
export type Time = bigint;
export type PresetId = bigint;
export type KeyframeId = bigint;
export interface KeyframeTrack {
    keyframes: Array<Keyframe>;
    propertyName: AnimatableProperty;
}
export interface Keyframe {
    id: KeyframeId;
    value: number;
    time: number;
    easing: EasingType;
}
export interface Effect {
    id: EffectId;
    keyframeTracks: Array<KeyframeTrack>;
    effectType: EffectType;
    params: Array<[string, number]>;
}
export interface Clip {
    id: ClipId;
    duration: number;
    keyframeTracks: Array<KeyframeTrack>;
    trimOut: number;
    effects: Array<Effect>;
    colorFilter: ColorFilter;
    trimIn: number;
    transition?: Transition;
    clipType: ClipType;
    volume: number;
    textProps?: TextClipProps;
    speed: number;
    trackId: TrackId;
    position: bigint;
    fileRef: string;
}
export type ClipId = bigint;
export interface TimelineSnapshot {
    musicTrack?: MusicTrack;
    clips: Array<Clip>;
}
export interface EffectPreset {
    id: PresetId;
    name: string;
    creatorId: Principal;
    effectType: EffectType;
    isPublic: boolean;
    params: Array<[string, number]>;
}
export interface MusicTrack {
    muted: boolean;
    volume: number;
    fileRef: string;
}
export interface Transition {
    duration: number;
    transitionType: TransitionType;
}
export type TrackId = bigint;
export type ProjectId = bigint;
export interface ProjectMeta {
    id: ProjectId;
    owner: Principal;
    name: string;
    createdAt: Time;
    totalDuration: number;
    lastModified: Time;
}
export interface TextClipProps {
    italic: boolean;
    content: string;
    bold: boolean;
    fontFamily: string;
    fontSize: number;
    alignment: Variant_center_left_right;
    fontColor: string;
}
export interface ColorFilter {
    contrast: number;
    hueRotation: number;
    brightness: number;
    opacity: number;
    saturation: number;
}
export enum AnimatableProperty {
    rotation = "rotation",
    shake_intensity = "shake_intensity",
    effect_intensity = "effect_intensity",
    scale_x = "scale_x",
    scale_y = "scale_y",
    blur_radius = "blur_radius",
    position_x = "position_x",
    position_y = "position_y",
    hue_shift = "hue_shift",
    shake_speed = "shake_speed",
    opacity = "opacity",
    saturation = "saturation"
}
export enum ClipType {
    audio = "audio",
    video = "video",
    text = "text",
    image = "image"
}
export enum EasingType {
    easeInOut = "easeInOut",
    bounce = "bounce",
    easeIn = "easeIn",
    easeOut = "easeOut",
    linear = "linear"
}
export enum EffectType {
    blur = "blur",
    shake = "shake",
    colorShift = "colorShift"
}
export enum Theme {
    dark = "dark",
    light = "light"
}
export enum TransitionType {
    zoom = "zoom",
    fadeToBlack = "fadeToBlack",
    slide = "slide",
    crossfade = "crossfade",
    dissolve = "dissolve"
}
export enum TransitionType__1 {
    blur = "blur",
    spin = "spin",
    zoom = "zoom",
    fadeToBlack = "fadeToBlack",
    slide = "slide",
    crossfade = "crossfade",
    glitch = "glitch",
    dissolve = "dissolve"
}
export enum Variant_center_left_right {
    center = "center",
    left = "left",
    right = "right"
}
export interface backendInterface {
    addClip(projectId: ProjectId, trackId: TrackId, fileRef: string, clipType: ClipType, duration: number): Promise<ClipId>;
    addEffect(projectId: ProjectId, clipId: ClipId, effectType: EffectType, params: Array<[string, number]>): Promise<EffectId>;
    addKeyframe(projectId: ProjectId, clipId: ClipId, propertyName: AnimatableProperty, time: number, value: number, easing: EasingType): Promise<KeyframeId>;
    createProject(name: string): Promise<ProjectMeta>;
    deletePreset(presetId: PresetId, isEffect: boolean): Promise<void>;
    deleteProject(projectId: ProjectId): Promise<void>;
    getClipKeyframeTracks(projectId: ProjectId, clipId: ClipId): Promise<Array<KeyframeTrack>>;
    getProject(projectId: ProjectId): Promise<Project | null>;
    getUserPreferences(): Promise<UserPreferences>;
    listEffectPresets(): Promise<Array<EffectPreset>>;
    listProjects(): Promise<Array<ProjectMeta>>;
    listTransitionPresets(): Promise<Array<TransitionPreset>>;
    redo(projectId: ProjectId): Promise<TimelineSnapshot | null>;
    removeClip(projectId: ProjectId, clipId: ClipId): Promise<void>;
    removeEffect(projectId: ProjectId, clipId: ClipId, effectId: EffectId): Promise<void>;
    removeKeyframe(projectId: ProjectId, clipId: ClipId, propertyName: AnimatableProperty, keyframeId: KeyframeId): Promise<void>;
    removeMusicTrack(projectId: ProjectId): Promise<void>;
    renameProject(projectId: ProjectId, newName: string): Promise<void>;
    reorderClip(projectId: ProjectId, clipId: ClipId, newPos: bigint): Promise<void>;
    saveEffectPreset(name: string, effectType: EffectType, params: Array<[string, number]>, isPublic: boolean): Promise<PresetId>;
    saveProject(projectId: ProjectId): Promise<ProjectMeta>;
    saveTransitionPreset(name: string, transitionType: TransitionType__1, params: Array<[string, number]>, isPublic: boolean): Promise<PresetId>;
    setMusicTrack(projectId: ProjectId, fileRef: string, volume: number): Promise<void>;
    setUserPreferences(prefs: UserPreferences): Promise<void>;
    undo(projectId: ProjectId): Promise<TimelineSnapshot | null>;
    updateClip(projectId: ProjectId, clipId: ClipId, fileRef: string | null, speed: number | null, volume: number | null, trimIn: number | null, trimOut: number | null, colorFilter: ColorFilter | null, transition: Some<Transition | null> | None): Promise<void>;
    updateEffect(projectId: ProjectId, clipId: ClipId, effectId: EffectId, params: Array<[string, number]>): Promise<void>;
    updateKeyframe(projectId: ProjectId, clipId: ClipId, propertyName: AnimatableProperty, keyframeId: KeyframeId, value: number | null, easing: EasingType | null): Promise<void>;
    updateMusicTrack(projectId: ProjectId, volume: number | null, muted: boolean | null): Promise<void>;
}
import type { AnimatableProperty as _AnimatableProperty, Clip as _Clip, ClipId as _ClipId, ClipType as _ClipType, ColorFilter as _ColorFilter, EasingType as _EasingType, Effect as _Effect, EffectId as _EffectId, EffectPreset as _EffectPreset, EffectType as _EffectType, Keyframe as _Keyframe, KeyframeId as _KeyframeId, KeyframeTrack as _KeyframeTrack, MusicTrack as _MusicTrack, PresetId as _PresetId, Project as _Project, ProjectMeta as _ProjectMeta, TextClipProps as _TextClipProps, Theme as _Theme, TimelineSnapshot as _TimelineSnapshot, TrackId as _TrackId, Transition as _Transition, TransitionPreset as _TransitionPreset, TransitionType as _TransitionType, TransitionType__1 as _TransitionType__1, UserPreferences as _UserPreferences } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addClip(arg0: ProjectId, arg1: TrackId, arg2: string, arg3: ClipType, arg4: number): Promise<ClipId> {
        if (this.processError) {
            try {
                const result = await this.actor.addClip(arg0, arg1, arg2, to_candid_ClipType_n1(this._uploadFile, this._downloadFile, arg3), arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addClip(arg0, arg1, arg2, to_candid_ClipType_n1(this._uploadFile, this._downloadFile, arg3), arg4);
            return result;
        }
    }
    async addEffect(arg0: ProjectId, arg1: ClipId, arg2: EffectType, arg3: Array<[string, number]>): Promise<EffectId> {
        if (this.processError) {
            try {
                const result = await this.actor.addEffect(arg0, arg1, to_candid_EffectType_n3(this._uploadFile, this._downloadFile, arg2), arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addEffect(arg0, arg1, to_candid_EffectType_n3(this._uploadFile, this._downloadFile, arg2), arg3);
            return result;
        }
    }
    async addKeyframe(arg0: ProjectId, arg1: ClipId, arg2: AnimatableProperty, arg3: number, arg4: number, arg5: EasingType): Promise<KeyframeId> {
        if (this.processError) {
            try {
                const result = await this.actor.addKeyframe(arg0, arg1, to_candid_AnimatableProperty_n5(this._uploadFile, this._downloadFile, arg2), arg3, arg4, to_candid_EasingType_n7(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addKeyframe(arg0, arg1, to_candid_AnimatableProperty_n5(this._uploadFile, this._downloadFile, arg2), arg3, arg4, to_candid_EasingType_n7(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async createProject(arg0: string): Promise<ProjectMeta> {
        if (this.processError) {
            try {
                const result = await this.actor.createProject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProject(arg0);
            return result;
        }
    }
    async deletePreset(arg0: PresetId, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePreset(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePreset(arg0, arg1);
            return result;
        }
    }
    async deleteProject(arg0: ProjectId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProject(arg0);
            return result;
        }
    }
    async getClipKeyframeTracks(arg0: ProjectId, arg1: ClipId): Promise<Array<KeyframeTrack>> {
        if (this.processError) {
            try {
                const result = await this.actor.getClipKeyframeTracks(arg0, arg1);
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClipKeyframeTracks(arg0, arg1);
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProject(arg0: ProjectId): Promise<Project | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProject(arg0);
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProject(arg0);
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserPreferences(): Promise<UserPreferences> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserPreferences();
                return from_candid_UserPreferences_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserPreferences();
            return from_candid_UserPreferences_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async listEffectPresets(): Promise<Array<EffectPreset>> {
        if (this.processError) {
            try {
                const result = await this.actor.listEffectPresets();
                return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listEffectPresets();
            return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async listProjects(): Promise<Array<ProjectMeta>> {
        if (this.processError) {
            try {
                const result = await this.actor.listProjects();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listProjects();
            return result;
        }
    }
    async listTransitionPresets(): Promise<Array<TransitionPreset>> {
        if (this.processError) {
            try {
                const result = await this.actor.listTransitionPresets();
                return from_candid_vec_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listTransitionPresets();
            return from_candid_vec_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async redo(arg0: ProjectId): Promise<TimelineSnapshot | null> {
        if (this.processError) {
            try {
                const result = await this.actor.redo(arg0);
                return from_candid_opt_n54(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.redo(arg0);
            return from_candid_opt_n54(this._uploadFile, this._downloadFile, result);
        }
    }
    async removeClip(arg0: ProjectId, arg1: ClipId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeClip(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeClip(arg0, arg1);
            return result;
        }
    }
    async removeEffect(arg0: ProjectId, arg1: ClipId, arg2: EffectId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeEffect(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeEffect(arg0, arg1, arg2);
            return result;
        }
    }
    async removeKeyframe(arg0: ProjectId, arg1: ClipId, arg2: AnimatableProperty, arg3: KeyframeId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeKeyframe(arg0, arg1, to_candid_AnimatableProperty_n5(this._uploadFile, this._downloadFile, arg2), arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeKeyframe(arg0, arg1, to_candid_AnimatableProperty_n5(this._uploadFile, this._downloadFile, arg2), arg3);
            return result;
        }
    }
    async removeMusicTrack(arg0: ProjectId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeMusicTrack(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeMusicTrack(arg0);
            return result;
        }
    }
    async renameProject(arg0: ProjectId, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.renameProject(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.renameProject(arg0, arg1);
            return result;
        }
    }
    async reorderClip(arg0: ProjectId, arg1: ClipId, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.reorderClip(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reorderClip(arg0, arg1, arg2);
            return result;
        }
    }
    async saveEffectPreset(arg0: string, arg1: EffectType, arg2: Array<[string, number]>, arg3: boolean): Promise<PresetId> {
        if (this.processError) {
            try {
                const result = await this.actor.saveEffectPreset(arg0, to_candid_EffectType_n3(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveEffectPreset(arg0, to_candid_EffectType_n3(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
            return result;
        }
    }
    async saveProject(arg0: ProjectId): Promise<ProjectMeta> {
        if (this.processError) {
            try {
                const result = await this.actor.saveProject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveProject(arg0);
            return result;
        }
    }
    async saveTransitionPreset(arg0: string, arg1: TransitionType__1, arg2: Array<[string, number]>, arg3: boolean): Promise<PresetId> {
        if (this.processError) {
            try {
                const result = await this.actor.saveTransitionPreset(arg0, to_candid_TransitionType__1_n57(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveTransitionPreset(arg0, to_candid_TransitionType__1_n57(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
            return result;
        }
    }
    async setMusicTrack(arg0: ProjectId, arg1: string, arg2: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setMusicTrack(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setMusicTrack(arg0, arg1, arg2);
            return result;
        }
    }
    async setUserPreferences(arg0: UserPreferences): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setUserPreferences(to_candid_UserPreferences_n59(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setUserPreferences(to_candid_UserPreferences_n59(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async undo(arg0: ProjectId): Promise<TimelineSnapshot | null> {
        if (this.processError) {
            try {
                const result = await this.actor.undo(arg0);
                return from_candid_opt_n54(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.undo(arg0);
            return from_candid_opt_n54(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateClip(arg0: ProjectId, arg1: ClipId, arg2: string | null, arg3: number | null, arg4: number | null, arg5: number | null, arg6: number | null, arg7: ColorFilter | null, arg8: Some<Transition | null> | None): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateClip(arg0, arg1, to_candid_opt_n63(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n64(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n64(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n64(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n64(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n65(this._uploadFile, this._downloadFile, arg7), to_candid_opt_n66(this._uploadFile, this._downloadFile, arg8));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateClip(arg0, arg1, to_candid_opt_n63(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n64(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n64(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n64(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n64(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n65(this._uploadFile, this._downloadFile, arg7), to_candid_opt_n66(this._uploadFile, this._downloadFile, arg8));
            return result;
        }
    }
    async updateEffect(arg0: ProjectId, arg1: ClipId, arg2: EffectId, arg3: Array<[string, number]>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEffect(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEffect(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateKeyframe(arg0: ProjectId, arg1: ClipId, arg2: AnimatableProperty, arg3: KeyframeId, arg4: number | null, arg5: EasingType | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateKeyframe(arg0, arg1, to_candid_AnimatableProperty_n5(this._uploadFile, this._downloadFile, arg2), arg3, to_candid_opt_n64(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n72(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateKeyframe(arg0, arg1, to_candid_AnimatableProperty_n5(this._uploadFile, this._downloadFile, arg2), arg3, to_candid_opt_n64(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n72(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async updateMusicTrack(arg0: ProjectId, arg1: number | null, arg2: boolean | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMusicTrack(arg0, to_candid_opt_n64(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n73(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMusicTrack(arg0, to_candid_opt_n64(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n73(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
}
function from_candid_AnimatableProperty_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AnimatableProperty): AnimatableProperty {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_ClipType_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ClipType): ClipType {
    return from_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function from_candid_Clip_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Clip): Clip {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_EasingType_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EasingType): EasingType {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_EffectPreset_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EffectPreset): EffectPreset {
    return from_candid_record_n48(_uploadFile, _downloadFile, value);
}
function from_candid_EffectType_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EffectType): EffectType {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid_Effect_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Effect): Effect {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_KeyframeTrack_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _KeyframeTrack): KeyframeTrack {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_Keyframe_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Keyframe): Keyframe {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_Project_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Project): Project {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_TextClipProps_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TextClipProps): TextClipProps {
    return from_candid_record_n40(_uploadFile, _downloadFile, value);
}
function from_candid_Theme_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Theme): Theme {
    return from_candid_variant_n45(_uploadFile, _downloadFile, value);
}
function from_candid_TimelineSnapshot_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TimelineSnapshot): TimelineSnapshot {
    return from_candid_record_n56(_uploadFile, _downloadFile, value);
}
function from_candid_TransitionPreset_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransitionPreset): TransitionPreset {
    return from_candid_record_n51(_uploadFile, _downloadFile, value);
}
function from_candid_TransitionType__1_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransitionType__1): TransitionType__1 {
    return from_candid_variant_n53(_uploadFile, _downloadFile, value);
}
function from_candid_TransitionType_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransitionType): TransitionType {
    return from_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function from_candid_Transition_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Transition): Transition {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_UserPreferences_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserPreferences): UserPreferences {
    return from_candid_record_n43(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Project]): Project | null {
    return value.length === 0 ? null : from_candid_Project_n20(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MusicTrack]): MusicTrack | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Transition]): Transition | null {
    return value.length === 0 ? null : from_candid_Transition_n32(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TextClipProps]): TextClipProps | null {
    return value.length === 0 ? null : from_candid_TextClipProps_n39(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TimelineSnapshot]): TimelineSnapshot | null {
    return value.length === 0 ? null : from_candid_TimelineSnapshot_n55(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    keyframes: Array<_Keyframe>;
    propertyName: _AnimatableProperty;
}): {
    keyframes: Array<Keyframe>;
    propertyName: AnimatableProperty;
} {
    return {
        keyframes: from_candid_vec_n12(_uploadFile, _downloadFile, value.keyframes),
        propertyName: from_candid_AnimatableProperty_n17(_uploadFile, _downloadFile, value.propertyName)
    };
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _KeyframeId;
    value: number;
    time: number;
    easing: _EasingType;
}): {
    id: KeyframeId;
    value: number;
    time: number;
    easing: EasingType;
} {
    return {
        id: value.id,
        value: value.value,
        time: value.time,
        easing: from_candid_EasingType_n15(_uploadFile, _downloadFile, value.easing)
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    musicTrack: [] | [_MusicTrack];
    meta: _ProjectMeta;
    clips: Array<_Clip>;
}): {
    musicTrack?: MusicTrack;
    meta: ProjectMeta;
    clips: Array<Clip>;
} {
    return {
        musicTrack: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.musicTrack)),
        meta: value.meta,
        clips: from_candid_vec_n23(_uploadFile, _downloadFile, value.clips)
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ClipId;
    duration: number;
    keyframeTracks: Array<_KeyframeTrack>;
    trimOut: number;
    effects: Array<_Effect>;
    colorFilter: _ColorFilter;
    trimIn: number;
    transition: [] | [_Transition];
    clipType: _ClipType;
    volume: number;
    textProps: [] | [_TextClipProps];
    speed: number;
    trackId: _TrackId;
    position: bigint;
    fileRef: string;
}): {
    id: ClipId;
    duration: number;
    keyframeTracks: Array<KeyframeTrack>;
    trimOut: number;
    effects: Array<Effect>;
    colorFilter: ColorFilter;
    trimIn: number;
    transition?: Transition;
    clipType: ClipType;
    volume: number;
    textProps?: TextClipProps;
    speed: number;
    trackId: TrackId;
    position: bigint;
    fileRef: string;
} {
    return {
        id: value.id,
        duration: value.duration,
        keyframeTracks: from_candid_vec_n9(_uploadFile, _downloadFile, value.keyframeTracks),
        trimOut: value.trimOut,
        effects: from_candid_vec_n26(_uploadFile, _downloadFile, value.effects),
        colorFilter: value.colorFilter,
        trimIn: value.trimIn,
        transition: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.transition)),
        clipType: from_candid_ClipType_n36(_uploadFile, _downloadFile, value.clipType),
        volume: value.volume,
        textProps: record_opt_to_undefined(from_candid_opt_n38(_uploadFile, _downloadFile, value.textProps)),
        speed: value.speed,
        trackId: value.trackId,
        position: value.position,
        fileRef: value.fileRef
    };
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _EffectId;
    keyframeTracks: Array<_KeyframeTrack>;
    effectType: _EffectType;
    params: Array<[string, number]>;
}): {
    id: EffectId;
    keyframeTracks: Array<KeyframeTrack>;
    effectType: EffectType;
    params: Array<[string, number]>;
} {
    return {
        id: value.id,
        keyframeTracks: from_candid_vec_n9(_uploadFile, _downloadFile, value.keyframeTracks),
        effectType: from_candid_EffectType_n29(_uploadFile, _downloadFile, value.effectType),
        params: value.params
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    duration: number;
    transitionType: _TransitionType;
}): {
    duration: number;
    transitionType: TransitionType;
} {
    return {
        duration: value.duration,
        transitionType: from_candid_TransitionType_n34(_uploadFile, _downloadFile, value.transitionType)
    };
}
function from_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    italic: boolean;
    content: string;
    bold: boolean;
    fontFamily: string;
    fontSize: number;
    alignment: {
        center: null;
    } | {
        left: null;
    } | {
        right: null;
    };
    fontColor: string;
}): {
    italic: boolean;
    content: string;
    bold: boolean;
    fontFamily: string;
    fontSize: number;
    alignment: Variant_center_left_right;
    fontColor: string;
} {
    return {
        italic: value.italic,
        content: value.content,
        bold: value.bold,
        fontFamily: value.fontFamily,
        fontSize: value.fontSize,
        alignment: from_candid_variant_n41(_uploadFile, _downloadFile, value.alignment),
        fontColor: value.fontColor
    };
}
function from_candid_record_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    theme: _Theme;
}): {
    theme: Theme;
} {
    return {
        theme: from_candid_Theme_n44(_uploadFile, _downloadFile, value.theme)
    };
}
function from_candid_record_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _PresetId;
    name: string;
    creatorId: Principal;
    effectType: _EffectType;
    isPublic: boolean;
    params: Array<[string, number]>;
}): {
    id: PresetId;
    name: string;
    creatorId: Principal;
    effectType: EffectType;
    isPublic: boolean;
    params: Array<[string, number]>;
} {
    return {
        id: value.id,
        name: value.name,
        creatorId: value.creatorId,
        effectType: from_candid_EffectType_n29(_uploadFile, _downloadFile, value.effectType),
        isPublic: value.isPublic,
        params: value.params
    };
}
function from_candid_record_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _PresetId;
    name: string;
    creatorId: Principal;
    transitionType: _TransitionType__1;
    isPublic: boolean;
    params: Array<[string, number]>;
}): {
    id: PresetId;
    name: string;
    creatorId: Principal;
    transitionType: TransitionType__1;
    isPublic: boolean;
    params: Array<[string, number]>;
} {
    return {
        id: value.id,
        name: value.name,
        creatorId: value.creatorId,
        transitionType: from_candid_TransitionType__1_n52(_uploadFile, _downloadFile, value.transitionType),
        isPublic: value.isPublic,
        params: value.params
    };
}
function from_candid_record_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    musicTrack: [] | [_MusicTrack];
    clips: Array<_Clip>;
}): {
    musicTrack?: MusicTrack;
    clips: Array<Clip>;
} {
    return {
        musicTrack: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.musicTrack)),
        clips: from_candid_vec_n23(_uploadFile, _downloadFile, value.clips)
    };
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    easeInOut: null;
} | {
    bounce: null;
} | {
    easeIn: null;
} | {
    easeOut: null;
} | {
    linear: null;
}): EasingType {
    return "easeInOut" in value ? EasingType.easeInOut : "bounce" in value ? EasingType.bounce : "easeIn" in value ? EasingType.easeIn : "easeOut" in value ? EasingType.easeOut : "linear" in value ? EasingType.linear : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    rotation: null;
} | {
    shake_intensity: null;
} | {
    effect_intensity: null;
} | {
    scale_x: null;
} | {
    scale_y: null;
} | {
    blur_radius: null;
} | {
    position_x: null;
} | {
    position_y: null;
} | {
    hue_shift: null;
} | {
    shake_speed: null;
} | {
    opacity: null;
} | {
    saturation: null;
}): AnimatableProperty {
    return "rotation" in value ? AnimatableProperty.rotation : "shake_intensity" in value ? AnimatableProperty.shake_intensity : "effect_intensity" in value ? AnimatableProperty.effect_intensity : "scale_x" in value ? AnimatableProperty.scale_x : "scale_y" in value ? AnimatableProperty.scale_y : "blur_radius" in value ? AnimatableProperty.blur_radius : "position_x" in value ? AnimatableProperty.position_x : "position_y" in value ? AnimatableProperty.position_y : "hue_shift" in value ? AnimatableProperty.hue_shift : "shake_speed" in value ? AnimatableProperty.shake_speed : "opacity" in value ? AnimatableProperty.opacity : "saturation" in value ? AnimatableProperty.saturation : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    blur: null;
} | {
    shake: null;
} | {
    colorShift: null;
}): EffectType {
    return "blur" in value ? EffectType.blur : "shake" in value ? EffectType.shake : "colorShift" in value ? EffectType.colorShift : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    zoom: null;
} | {
    fadeToBlack: null;
} | {
    slide: null;
} | {
    crossfade: null;
} | {
    dissolve: null;
}): TransitionType {
    return "zoom" in value ? TransitionType.zoom : "fadeToBlack" in value ? TransitionType.fadeToBlack : "slide" in value ? TransitionType.slide : "crossfade" in value ? TransitionType.crossfade : "dissolve" in value ? TransitionType.dissolve : value;
}
function from_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    audio: null;
} | {
    video: null;
} | {
    text: null;
} | {
    image: null;
}): ClipType {
    return "audio" in value ? ClipType.audio : "video" in value ? ClipType.video : "text" in value ? ClipType.text : "image" in value ? ClipType.image : value;
}
function from_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    center: null;
} | {
    left: null;
} | {
    right: null;
}): Variant_center_left_right {
    return "center" in value ? Variant_center_left_right.center : "left" in value ? Variant_center_left_right.left : "right" in value ? Variant_center_left_right.right : value;
}
function from_candid_variant_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    dark: null;
} | {
    light: null;
}): Theme {
    return "dark" in value ? Theme.dark : "light" in value ? Theme.light : value;
}
function from_candid_variant_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    blur: null;
} | {
    spin: null;
} | {
    zoom: null;
} | {
    fadeToBlack: null;
} | {
    slide: null;
} | {
    crossfade: null;
} | {
    glitch: null;
} | {
    dissolve: null;
}): TransitionType__1 {
    return "blur" in value ? TransitionType__1.blur : "spin" in value ? TransitionType__1.spin : "zoom" in value ? TransitionType__1.zoom : "fadeToBlack" in value ? TransitionType__1.fadeToBlack : "slide" in value ? TransitionType__1.slide : "crossfade" in value ? TransitionType__1.crossfade : "glitch" in value ? TransitionType__1.glitch : "dissolve" in value ? TransitionType__1.dissolve : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Keyframe>): Array<Keyframe> {
    return value.map((x)=>from_candid_Keyframe_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Clip>): Array<Clip> {
    return value.map((x)=>from_candid_Clip_n24(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Effect>): Array<Effect> {
    return value.map((x)=>from_candid_Effect_n27(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_EffectPreset>): Array<EffectPreset> {
    return value.map((x)=>from_candid_EffectPreset_n47(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TransitionPreset>): Array<TransitionPreset> {
    return value.map((x)=>from_candid_TransitionPreset_n50(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_KeyframeTrack>): Array<KeyframeTrack> {
    return value.map((x)=>from_candid_KeyframeTrack_n10(_uploadFile, _downloadFile, x));
}
function to_candid_AnimatableProperty_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AnimatableProperty): _AnimatableProperty {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_ClipType_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ClipType): _ClipType {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_EasingType_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EasingType): _EasingType {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_EffectType_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EffectType): _EffectType {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_Theme_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Theme): _Theme {
    return to_candid_variant_n62(_uploadFile, _downloadFile, value);
}
function to_candid_TransitionType__1_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransitionType__1): _TransitionType__1 {
    return to_candid_variant_n58(_uploadFile, _downloadFile, value);
}
function to_candid_TransitionType_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransitionType): _TransitionType {
    return to_candid_variant_n71(_uploadFile, _downloadFile, value);
}
function to_candid_Transition_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Transition): _Transition {
    return to_candid_record_n69(_uploadFile, _downloadFile, value);
}
function to_candid_UserPreferences_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserPreferences): _UserPreferences {
    return to_candid_record_n60(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: number | null): [] | [number] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ColorFilter | null): [] | [_ColorFilter] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Some<Transition | null> | None): [] | [[] | [_Transition]] {
    return isNone(value) ? candid_none() : candid_some(to_candid_opt_n67(_uploadFile, _downloadFile, unwrap(value)));
}
function to_candid_opt_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Transition | null): [] | [_Transition] {
    return value === null ? candid_none() : candid_some(to_candid_Transition_n68(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n72(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EasingType | null): [] | [_EasingType] {
    return value === null ? candid_none() : candid_some(to_candid_EasingType_n7(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n73(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: boolean | null): [] | [boolean] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    theme: Theme;
}): {
    theme: _Theme;
} {
    return {
        theme: to_candid_Theme_n61(_uploadFile, _downloadFile, value.theme)
    };
}
function to_candid_record_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    duration: number;
    transitionType: TransitionType;
}): {
    duration: number;
    transitionType: _TransitionType;
} {
    return {
        duration: value.duration,
        transitionType: to_candid_TransitionType_n70(_uploadFile, _downloadFile, value.transitionType)
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ClipType): {
    audio: null;
} | {
    video: null;
} | {
    text: null;
} | {
    image: null;
} {
    return value == ClipType.audio ? {
        audio: null
    } : value == ClipType.video ? {
        video: null
    } : value == ClipType.text ? {
        text: null
    } : value == ClipType.image ? {
        image: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EffectType): {
    blur: null;
} | {
    shake: null;
} | {
    colorShift: null;
} {
    return value == EffectType.blur ? {
        blur: null
    } : value == EffectType.shake ? {
        shake: null
    } : value == EffectType.colorShift ? {
        colorShift: null
    } : value;
}
function to_candid_variant_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransitionType__1): {
    blur: null;
} | {
    spin: null;
} | {
    zoom: null;
} | {
    fadeToBlack: null;
} | {
    slide: null;
} | {
    crossfade: null;
} | {
    glitch: null;
} | {
    dissolve: null;
} {
    return value == TransitionType__1.blur ? {
        blur: null
    } : value == TransitionType__1.spin ? {
        spin: null
    } : value == TransitionType__1.zoom ? {
        zoom: null
    } : value == TransitionType__1.fadeToBlack ? {
        fadeToBlack: null
    } : value == TransitionType__1.slide ? {
        slide: null
    } : value == TransitionType__1.crossfade ? {
        crossfade: null
    } : value == TransitionType__1.glitch ? {
        glitch: null
    } : value == TransitionType__1.dissolve ? {
        dissolve: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AnimatableProperty): {
    rotation: null;
} | {
    shake_intensity: null;
} | {
    effect_intensity: null;
} | {
    scale_x: null;
} | {
    scale_y: null;
} | {
    blur_radius: null;
} | {
    position_x: null;
} | {
    position_y: null;
} | {
    hue_shift: null;
} | {
    shake_speed: null;
} | {
    opacity: null;
} | {
    saturation: null;
} {
    return value == AnimatableProperty.rotation ? {
        rotation: null
    } : value == AnimatableProperty.shake_intensity ? {
        shake_intensity: null
    } : value == AnimatableProperty.effect_intensity ? {
        effect_intensity: null
    } : value == AnimatableProperty.scale_x ? {
        scale_x: null
    } : value == AnimatableProperty.scale_y ? {
        scale_y: null
    } : value == AnimatableProperty.blur_radius ? {
        blur_radius: null
    } : value == AnimatableProperty.position_x ? {
        position_x: null
    } : value == AnimatableProperty.position_y ? {
        position_y: null
    } : value == AnimatableProperty.hue_shift ? {
        hue_shift: null
    } : value == AnimatableProperty.shake_speed ? {
        shake_speed: null
    } : value == AnimatableProperty.opacity ? {
        opacity: null
    } : value == AnimatableProperty.saturation ? {
        saturation: null
    } : value;
}
function to_candid_variant_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Theme): {
    dark: null;
} | {
    light: null;
} {
    return value == Theme.dark ? {
        dark: null
    } : value == Theme.light ? {
        light: null
    } : value;
}
function to_candid_variant_n71(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransitionType): {
    zoom: null;
} | {
    fadeToBlack: null;
} | {
    slide: null;
} | {
    crossfade: null;
} | {
    dissolve: null;
} {
    return value == TransitionType.zoom ? {
        zoom: null
    } : value == TransitionType.fadeToBlack ? {
        fadeToBlack: null
    } : value == TransitionType.slide ? {
        slide: null
    } : value == TransitionType.crossfade ? {
        crossfade: null
    } : value == TransitionType.dissolve ? {
        dissolve: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EasingType): {
    easeInOut: null;
} | {
    bounce: null;
} | {
    easeIn: null;
} | {
    easeOut: null;
} | {
    linear: null;
} {
    return value == EasingType.easeInOut ? {
        easeInOut: null
    } : value == EasingType.bounce ? {
        bounce: null
    } : value == EasingType.easeIn ? {
        easeIn: null
    } : value == EasingType.easeOut ? {
        easeOut: null
    } : value == EasingType.linear ? {
        linear: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
